[package]
name = "tpfl"
version = "0.0.1"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_yml = "0.0.12"
xdg = "3.0.0"
